### PR TITLE
for the moment finished seo optimized project site

### PR DESCRIPTION
**Pull request by marki155**
translations added

### CODE REVIEW

**Comment by Zethson** [comment]
@marki155 I see a lot of outcommented translations and deleted translations at the very bottom of the translations file.
Could you please verify that all translations are still working and then delete the outcommented translations?

I'll then happily merge this!

Thanks!

**Comment by marki155** [comment]
The outcommented translations aren't checked yet. I want to make sure if the changes are fine. Afterwards I'll translate it and check this.

**Comment by Zethson** [comment]
I have a few minor changes. I'll do them this weekend. 

Thanks @marki155 !

**Comment by Zethson** [comment]
@marki155 I really feel like this is too SEO aggressive. Some of the renamings may improve the SEO, but are repetitive and make the site harder to navigate. 

Example: "History of genetic engineering projects" may be for the SEO, but really doesn't fit the site anymore. It's about the history of all iGEM Tübingen projects, not about genetic engineering projects in general.

Also, Google penalizes sites who SEO too hard. I'll change a few of the things tonight.

**Comment by Zethson** [comment]
@marki155 Pushed some changes. Generally I really like your approach!

@Imipenem Could you also review this briefly? What do you think?

@marki155 After @Imipenem gave his approval I guess you could start with the translations.

Thanks!

**Comment by Imipenem** [comment]
- I really like the refactoring of the projects repetitive code snippets like footers etc. This definitely improves maintainability; nice work.

- I did not read in too much detail, but the renamings should be good for now

- _One more thing_: We should refactor the projects structure especially the "templates" directory: It´s quite confusing with all those html templates in the main directory
They should be grouped together like the error templates and the banner

But all told: Very nice changes and everything looks good imo.

**Review by Imipenem — APPROVED** [review]

**Comment by Zethson** [comment]
> One more thing: We should refactor the projects structure especially the "templates" directory: It´s quite confusing with all those html templates in the main directory
They should be grouped together like the error templates and the banner

True. But should be done in another PR.

@marki155 Awaiting the translations ;)

**Comment by marki155** [comment]
@Zethson I viewed your changes. I also think this is more content based now, thanks.
I'll now do the translations

**Comment by Zethson** [comment]
I'll fix the conflicts and review asap.
Might take some time though, will see..

**Comment by Zethson** [comment]
Let's wait for a new sponsors image by @famosab ...
Then I'll give it a try I guess.

**Pull request merged**
